/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;
import Config.DbConfig;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Arga 'Ahmad Mujahidin' Herlambang
 */
public class CRUDrute extends javax.swing.JFrame {
    Connection conn=DbConfig.getConnection();
    DefaultTableModel tabmodel;
    DefaultComboBoxModel combomodel;
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
    DecimalFormat dformatter = new DecimalFormat("#,###0");
    Integer selected = null;
    String updatetext = "Update";
    String deletetext = "Delete";
    ArrayList<Integer> arraytype = null;
    
    public void judul() {
        String[] judul = {
            "ID","Tujuan","Rute Awal","Rute Akhir","Harga","Transportasi"
        };
        tabmodel = new DefaultTableModel(null, judul);
        table_rute.setModel(tabmodel);
    }
    
    public void showCombo() {
        arraytype = new ArrayList<Integer>();
        String [] selects = {
            " "
        };
        combomodel = new DefaultComboBoxModel(selects);
        combo_transportasi.setModel(combomodel);
        try {
            Statement stat = conn.createStatement();
            ResultSet resu = stat.executeQuery("SELECT id_transportasi,kode FROM transportasi");
            while (resu.next()) {
                arraytype.add(resu.getInt("id_transportasi"));
                combomodel.addElement(resu.getString("kode"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void showData() {
        try {
            System.out.println("asdasdddd");
            Statement stat = conn.createStatement();
            tabmodel.getDataVector().removeAllElements();
            tabmodel.fireTableDataChanged();
            ResultSet resu = stat.executeQuery("SELECT * FROM rute");
            while (resu.next()) {
                    String type = null;
                    Statement sta1 = conn.createStatement();
                    ResultSet res1 = sta1.executeQuery("SELECT kode FROM transportasi WHERE id_transportasi="+resu.getString("id_transportasi"));
                    Boolean res2 = res1.next();
                    if (res2==true) {
                        type=res1.getString("kode");
                    }
                Object[] data = {
                    resu.getInt("id_rute"),
                    resu.getString("tujuan"),
                    resu.getString("rute_awal"),
                    resu.getString("rute_ahir"),
                    String.format("%,d",resu.getInt("harga")),
                    type
                };
                tabmodel.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void ebutton(Boolean p) {
        if (p==true) {
            btn_Update.setText(updatetext+" ("+selected+")");
            btn_Delete.setText(deletetext+" ("+selected+")");
        } else {
            selected = null;
            btn_Update.setText(updatetext);
            btn_Delete.setText(deletetext);
        }
        btn_Update.setEnabled(p);
        btn_Delete.setEnabled(p);
    }
    /**
     * Creates new form CRUD
     */
    public CRUDrute() {
        initComponents();
        showCombo();
        judul();
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_rute = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_tujuan = new javax.swing.JTextField();
        combo_transportasi = new javax.swing.JComboBox<>();
        txt_harga = new javax.swing.JFormattedTextField();
        btn_Add = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_ruteawal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_ruteahir = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel4.setText("jLabel4");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_rute.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_rute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_ruteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_rute);

        jLabel1.setText("Rute");

        jLabel2.setText("Tujuan");

        jLabel9.setText("Transportasi");

        jLabel10.setText("Harga");

        combo_transportasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Laki-Laki", "Perempuan" }));

        txt_harga.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        btn_Add.setText("Add");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        btn_Update.setText("Update");
        btn_Update.setEnabled(false);
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        btn_Delete.setText("Delete");
        btn_Delete.setEnabled(false);
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel3.setText("Rute Awal");

        jLabel5.setText("Rute Akhir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_ruteahir, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_ruteawal, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(combo_transportasi, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(txt_tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_Delete)
                            .addComponent(btn_Add))
                        .addGap(254, 254, 254)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Update)
                            .addComponent(Back))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_ruteawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_ruteahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(combo_transportasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Add)
                            .addComponent(btn_Update))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Delete)
                            .addComponent(Back))))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        // TODO add your handling code here:
//        System.out.println("asdasd");
//        String kelamin = null;
//        if (combo_tipetransportasi.getSelectedIndex() == 1) {
//            kelamin = "Laki-laki";
//        } else if (combo_tipetransportasi.getSelectedIndex() == 2) {
//            kelamin = "Perempuan";
//        }
        try {
            System.out.println("asdasdaaa");
            Statement stat = conn.createStatement();
            String query = "INSERT INTO rute VALUES(NULL,'"+txt_tujuan.getText()+"','"+txt_ruteawal.getText()+"','"+txt_ruteahir.getText()+"',"+Integer.parseInt(txt_harga.getText().replaceAll("[^0-9]", ""))+","+arraytype.get(combo_transportasi.getSelectedIndex()-1)+")";
            System.out.println(query);
            stat.executeUpdate(query);
            showData();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
        }
        
//        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
//        
//        JOptionPane.showMessageDialog(this, formatter.format(date_tanggallahir.getDate()));
    }//GEN-LAST:event_btn_AddActionPerformed

    private void table_ruteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_ruteMouseClicked
        // TODO add your handling code here:
        try {
            System.out.println("asdasdaaa");
            Statement stat = conn.createStatement();
            String query = "SELECT * FROM rute WHERE id_rute="+table_rute.getValueAt(table_rute.getSelectedRow(), 0).toString();
            System.out.println(query);
            ResultSet resu = stat.executeQuery(query);
            if (resu.next()==true) {
                selected = resu.getInt("id_rute");
                txt_tujuan.setText(resu.getString("tujuan"));
                txt_ruteawal.setText(resu.getString("rute_awal"));
                txt_ruteahir.setText(resu.getString("rute_ahir"));
                txt_harga.setText(String.format("%,d",resu.getInt("harga")));
                combo_transportasi.setSelectedIndex(arraytype.indexOf(resu.getInt("id_transportasi"))+1);
            }
            showData();
            ebutton(true);
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
        }
//        selected = Integer.parseInt(table_penumpang.getValueAt(table_penumpang.getSelectedRow(), 0).toString());
//        txt_username.setText(table_penumpang.getValueAt(table_penumpang.getSelectedRow(), 1).toString());
//        txt_password.setText(table_penumpang.getValueAt(table_penumpang.getSelectedRow(), 2).toString());
//        txt_namapenumpang.setText(table_penumpang.getValueAt(table_penumpang.getSelectedRow(), 3).toString());
//        txt_alamatpenumpang.setText(table_penumpang.getValueAt(table_penumpang.getSelectedRow(), 4).toString());
//        try {
//            date_tanggallahir.setDate(formatter.parse(table_penumpang.getValueAt(table_penumpang.getSelectedRow(), 5).toString()));
//        } catch (ParseException ex) {
//            Logger.getLogger(CRUDtransportasi.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        if (table_penumpang.getValueAt(table_penumpang.getSelectedRow(), 6).toString().equals("Laki-laki")) {
//            combo_tipetransportasi.setSelectedIndex(1);
//        } else if (table_penumpang.getValueAt(table_penumpang.getSelectedRow(), 6).toString().equals("Perempuan")) {
//            combo_tipetransportasi.setSelectedIndex(2);
//        }
//        txt_telefone.setText(table_penumpang.getValueAt(table_penumpang.getSelectedRow(), 0).toString());
//        ebutton(true);
    }//GEN-LAST:event_table_ruteMouseClicked

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
        if (selected != null) {
//            String kelamin = null;
//        if (combo_tipetransportasi.getSelectedIndex() == 1) {
//            kelamin = "Laki-laki";
//        } else if (combo_tipetransportasi.getSelectedIndex() == 2) {
//            kelamin = "Perempuan";
//        }
        try {
            System.out.println("asdasdaaa");
            Statement stat = conn.createStatement();
            String query = "UPDATE rute SET "
                    + "tujuan='"+txt_tujuan.getText()+"', "
                    + "ruteawal='"+txt_ruteawal.getText()+"', "
                    + "ruteahir='"+txt_ruteahir.getText()+"', "
                    + "harga="+Integer.parseInt(txt_harga.getText().replaceAll("[^0-9]", ""))+", "
                    + "id_transportasi="+arraytype.get(combo_transportasi.getSelectedIndex()-1)+" "
                    + "WHERE id_rute="+selected;
            System.out.println(query);
            stat.executeUpdate(query);
            showData();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
        }
        }
//        
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // TODO add your handling code here:
        if (selected != null) {
            
        try {
            System.out.println("asdasdaaa");
            Statement stat = conn.createStatement();
            String query = "DELETE FROM rute WHERE id_rute="+selected;
            System.out.println(query);
            stat.executeUpdate(query);
            showData();
            ebutton(false);
            
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        CRUD a = new CRUD();
        a.setVisible(true);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDrute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDrute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDrute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDrute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDrute().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Update;
    private javax.swing.JComboBox<String> combo_transportasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable table_rute;
    private javax.swing.JFormattedTextField txt_harga;
    private javax.swing.JTextField txt_ruteahir;
    private javax.swing.JTextField txt_ruteawal;
    private javax.swing.JTextField txt_tujuan;
    // End of variables declaration//GEN-END:variables
}
