/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;
import Config.DbConfig;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Arga 'Ahmad Mujahidin' Herlambang
 */
public class CRUDpetugas extends javax.swing.JFrame {
    Connection conn=DbConfig.getConnection();
    DefaultTableModel tabmodel;
    DefaultComboBoxModel combomodel;
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
    Integer selected = null;
    String updatetext = "Update";
    String deletetext = "Delete";
    ArrayList<Integer> arraytype = null;
    
    public void judul() {
        String[] judul = {
            "ID","Kode","Jumlah Kursi","Keterangan","Tipe Transportasi"
        };
        tabmodel = new DefaultTableModel(null, judul);
        table_penumpang.setModel(tabmodel);
    }
    
    public void showCombo() {
        arraytype = new ArrayList<Integer>();
        String [] selects = {
            " "
        };
        combomodel = new DefaultComboBoxModel(selects);
        combo_tipetransportasi.setModel(combomodel);
        try {
            Statement stat = conn.createStatement();
            ResultSet resu = stat.executeQuery("SELECT id_type_transportasi,nama_type FROM type_transportasi");
            while (resu.next()) {
                arraytype.add(resu.getInt("id_type_transportasi"));
                combomodel.addElement(resu.getString("nama_type"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void showData() {
        try {
            System.out.println("asdasdddd");
            Statement stat = conn.createStatement();
            tabmodel.getDataVector().removeAllElements();
            tabmodel.fireTableDataChanged();
            ResultSet resu = stat.executeQuery("SELECT * FROM transportasi");
            while (resu.next()) {
                    String type = null;
                    Statement sta1 = conn.createStatement();
                    ResultSet res1 = sta1.executeQuery("SELECT nama_type FROM type_transportasi WHERE id_type_transportasi="+resu.getString("id_type_transportasi"));
                    Boolean res2 = res1.next();
                    if (res2==true) {
                        type=res1.getString("nama_type");
                    }
                Object[] data = {
                    resu.getInt("id_transportasi"),
                    resu.getString("kode"),
                    resu.getInt("jumlah_kursi"),
                    resu.getString("keterangan"),
                    type
                };
                tabmodel.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void ebutton(Boolean p) {
        if (p==true) {
            btn_Update.setText(updatetext+" ("+selected+")");
            btn_Delete.setText(deletetext+" ("+selected+")");
        } else {
            selected = null;
            btn_Update.setText(updatetext);
            btn_Delete.setText(deletetext);
        }
        btn_Update.setEnabled(p);
        btn_Delete.setEnabled(p);
    }
    /**
     * Creates new form CRUD
     */
    public CRUDpetugas() {
        initComponents();
        showCombo();
        judul();
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_penumpang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_kode = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_keterangan = new javax.swing.JTextArea();
        combo_tipetransportasi = new javax.swing.JComboBox<>();
        txt_jumlahkursi = new javax.swing.JFormattedTextField();
        btn_Add = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel4.setText("jLabel4");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_penumpang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_penumpang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_penumpangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_penumpang);

        jLabel1.setText("Transportasi");

        jLabel2.setText("Kode");

        jLabel7.setText("Keterangan");

        jLabel9.setText("Tipe Transportasi");

        jLabel10.setText("Jumlah Kursi");

        txt_keterangan.setColumns(20);
        txt_keterangan.setRows(5);
        jScrollPane3.setViewportView(txt_keterangan);

        combo_tipetransportasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Laki-Laki", "Perempuan" }));

        txt_jumlahkursi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));

        btn_Add.setText("Add");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        btn_Update.setText("Update");
        btn_Update.setEnabled(false);
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        btn_Delete.setText("Delete");
        btn_Delete.setEnabled(false);
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_jumlahkursi, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combo_tipetransportasi, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                                .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_Delete)
                                    .addComponent(btn_Add))
                                .addGap(254, 254, 254)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_Update)
                                    .addComponent(Back))))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_jumlahkursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(combo_tipetransportasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Add)
                            .addComponent(btn_Update))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Delete)
                            .addComponent(Back))))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        // TODO add your handling code here:
//        System.out.println("asdasd");
//        String kelamin = null;
//        if (combo_tipetransportasi.getSelectedIndex() == 1) {
//            kelamin = "Laki-laki";
//        } else if (combo_tipetransportasi.getSelectedIndex() == 2) {
//            kelamin = "Perempuan";
//        }
        try {
            System.out.println("asdasdaaa");
            Statement stat = conn.createStatement();
            String query = "INSERT INTO transportasi VALUES(NULL,'"+txt_kode.getText()+"','"+txt_jumlahkursi.getText()+"','"+txt_keterangan.getText()+"',"+arraytype.get(combo_tipetransportasi.getSelectedIndex()-1)+")";
            System.out.println(query);
            stat.executeUpdate(query);
            showData();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
        }
        
//        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
//        
//        JOptionPane.showMessageDialog(this, formatter.format(date_tanggallahir.getDate()));
    }//GEN-LAST:event_btn_AddActionPerformed

    private void table_penumpangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_penumpangMouseClicked
        // TODO add your handling code here:
        try {
            System.out.println("asdasdaaa");
            Statement stat = conn.createStatement();
            String query = "SELECT * FROM transportasi WHERE id_transportasi="+table_penumpang.getValueAt(table_penumpang.getSelectedRow(), 0).toString();
            System.out.println(query);
            ResultSet resu = stat.executeQuery(query);
            if (resu.next()==true) {
                selected = resu.getInt("id_transportasi");
                txt_kode.setText(resu.getString("kode"));
                txt_jumlahkursi.setText(resu.getString("jumlah_kursi"));
                txt_keterangan.setText(resu.getString("keterangan"));
                combo_tipetransportasi.setSelectedIndex(arraytype.indexOf(resu.getInt("id_type_transportasi"))+1);
            }
            showData();
            ebutton(true);
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
        }
//        selected = Integer.parseInt(table_penumpang.getValueAt(table_penumpang.getSelectedRow(), 0).toString());
//        txt_username.setText(table_penumpang.getValueAt(table_penumpang.getSelectedRow(), 1).toString());
//        txt_password.setText(table_penumpang.getValueAt(table_penumpang.getSelectedRow(), 2).toString());
//        txt_namapenumpang.setText(table_penumpang.getValueAt(table_penumpang.getSelectedRow(), 3).toString());
//        txt_alamatpenumpang.setText(table_penumpang.getValueAt(table_penumpang.getSelectedRow(), 4).toString());
//        try {
//            date_tanggallahir.setDate(formatter.parse(table_penumpang.getValueAt(table_penumpang.getSelectedRow(), 5).toString()));
//        } catch (ParseException ex) {
//            Logger.getLogger(CRUDtransportasi.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        if (table_penumpang.getValueAt(table_penumpang.getSelectedRow(), 6).toString().equals("Laki-laki")) {
//            combo_tipetransportasi.setSelectedIndex(1);
//        } else if (table_penumpang.getValueAt(table_penumpang.getSelectedRow(), 6).toString().equals("Perempuan")) {
//            combo_tipetransportasi.setSelectedIndex(2);
//        }
//        txt_telefone.setText(table_penumpang.getValueAt(table_penumpang.getSelectedRow(), 0).toString());
//        ebutton(true);
    }//GEN-LAST:event_table_penumpangMouseClicked

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
        if (selected != null) {
//            String kelamin = null;
//        if (combo_tipetransportasi.getSelectedIndex() == 1) {
//            kelamin = "Laki-laki";
//        } else if (combo_tipetransportasi.getSelectedIndex() == 2) {
//            kelamin = "Perempuan";
//        }
        try {
            System.out.println("asdasdaaa");
            Statement stat = conn.createStatement();
            String query = "UPDATE transportasi SET "
                    + "kode='"+txt_kode.getText()+"', "
                    + "jumlah_kursi="+Integer.parseInt(txt_jumlahkursi.getText())+", "
                    + "keterangan='"+txt_keterangan.getText()+"', "
                    + "id_type_transportasi="+arraytype.get(combo_tipetransportasi.getSelectedIndex()-1)+" "
                    + "WHERE id_transportasi="+selected;
            System.out.println(query);
            stat.executeUpdate(query);
            showData();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
        }
        }
//        
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // TODO add your handling code here:
        if (selected != null) {
            
        try {
            System.out.println("asdasdaaa");
            Statement stat = conn.createStatement();
            String query = "DELETE FROM transportasi WHERE id_transportasi="+selected;
            System.out.println(query);
            stat.executeUpdate(query);
            showData();
            ebutton(false);
            
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        CRUD a = new CRUD();
        a.setVisible(true);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDpetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDpetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDpetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDpetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDpetugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Update;
    private javax.swing.JComboBox<String> combo_tipetransportasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable table_penumpang;
    private javax.swing.JFormattedTextField txt_jumlahkursi;
    private javax.swing.JTextArea txt_keterangan;
    private javax.swing.JTextField txt_kode;
    // End of variables declaration//GEN-END:variables
}
