/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Config.DbConfig;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arga 'Ahmad Mujahidin' Herlambang
 */
public class LihatTicket extends javax.swing.JFrame {
    /**
     * Creates new form PesanTicket
     */
    Integer userid=null;
    
    Connection conn=DbConfig.getConnection();
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
    ArrayList<Integer> arraytype=null;
    ArrayList<Integer> arraytugas=null;
    DefaultTableModel tabmodel;
    
    public void judul() {
        String[] judul = {
            "ID","Kode","Tanggal Pemesanan","Tempat Pemesanan","Kursi","Tujuan","Rute","Tanggal Berangkat","Jam Cekin","Jam Berangkat","Pembayaran","Petugas"
        };
        tabmodel = new DefaultTableModel(null, judul);
        table_pemesanan.setModel(tabmodel);
    }
    
    public void showData() {
        try {
            System.out.println("asdasdddd");
            Statement stat = conn.createStatement();
            tabmodel.getDataVector().removeAllElements();
            tabmodel.fireTableDataChanged();
            ResultSet resu = stat.executeQuery("SELECT * FROM pemesanan WHERE id_pelanggan="+userid);
            while (resu.next()) {
                    String tujuan = null;
                    String ruteawal = null;
                    String ruteahir = null;
                    String harga = null;
                    String petugas = null;
                    ResultSet res1 = conn.createStatement().executeQuery("SELECT tujuan FROM rute WHERE id_rute="+resu.getString("id_rute"));
                    if (res1.next()==true) {
                        tujuan=res1.getString("tujuan");
                    }
                    ResultSet res2 = conn.createStatement().executeQuery("SELECT rute_awal FROM rute WHERE id_rute="+resu.getString("id_rute"));
                    if (res2.next()==true) {
                        ruteawal=res2.getString("rute_awal");
                    }
                    ResultSet res3 = conn.createStatement().executeQuery("SELECT rute_ahir FROM rute WHERE id_rute="+resu.getString("id_rute"));
                    if (res3.next()==true) {
                        ruteahir=res3.getString("rute_ahir");
                    }
                    ResultSet res4 = conn.createStatement().executeQuery("SELECT harga FROM rute WHERE id_rute="+resu.getString("id_rute"));
                    if (res4.next()==true) {
                        harga=res4.getString("harga");
                    }
                    ResultSet res5 = conn.createStatement().executeQuery("SELECT nama_petugas FROM petugas WHERE id_petugas="+resu.getString("id_petugas"));
                    if (res5.next()==true) {
                        petugas=res5.getString("nama_petugas");
                    }
                Object[] data = {
                    resu.getInt("id_rute"),
                    resu.getString("kode_pemesanan"),
                    resu.getString("tanggal_pemesanan"),
                    resu.getString("tempat_pemesanan"),
                    resu.getString("kode_kursi"),
                    tujuan,
                    ruteawal+" - "+ruteahir,
                    resu.getString("tanggal_berangkat"),
                    resu.getString("jam_cekin"),
                    resu.getString("jam_berangkat"),
                    String.format("%,d",Integer.parseInt(harga)),
                    petugas
                };
                tabmodel.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public LihatTicket(Integer uid,String nama) {
            initComponents();
        if (uid!=null) {
            userid=uid;
            txt_idpenumpang.setText(nama);
            judul();
            showData();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        txt_idpenumpang = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_pemesanan = new javax.swing.JTable();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_idpenumpang.setText("User");

        table_pemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_pemesanan);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_idpenumpang)
                .addGap(95, 95, 95)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_idpenumpang))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LihatTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LihatTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LihatTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LihatTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LihatTicket(null,"").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_pemesanan;
    private javax.swing.JLabel txt_idpenumpang;
    // End of variables declaration//GEN-END:variables
}
